sudo: required
language: scala
jdk:
  - openjdk9
branches:
  only:
    - master
    - sigma-v2.1
scala:
  - 2.12.8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script:
  - sbt clean test
after_success:
  - sbt publish
env:
  global:
    - secure: wXzNFySOhhx6b3EkokyC8SlLJrUYMDCOLKwEDbd98ly52BosPSukAgPljepXbnLU6DQ5TrHxxXYp+K9PTSpfxYyGYmt2JZPZTK5wcdp3hCD/ZY2Fi+mgUM2Cvk4oGyIuV21jKRnl2N28N80jOjoTy0jiMbD5v6kwtYCtzU+0VgTDO9pjmILi+18qoKcQn9btsm+qGJK8eYf4FU7mjAF+XtZbSduzcHX+mRvoYR/fS9/pHYkAKs0uIbPrY92vH1ahurLccXyPV5Rz7RqQ33GAURMnHDJlNEJpdurC0tQ8IdrVNdytUUXxyGCQOz/Xnl8KD9pttrYeX2nwQ9xaNql4DHN+zw8gjxen0VpE9p7+Bj7UbP+C3SiV1FBfzX35WwCUilphpwITT/zBx7VBPDkOcLsPm21EODWYp2EvvCsssKKiNuCGpCt12afZXQz21FJWKyM6f9iKqbBLEiFS2XwPigAMQ+hKj4crFb5mCGBGSVrtKJAiyBQ+uI2cGA44NhmwBPdvDw0hVVPWyOuiQH/sRzpSxsRXOMwj1+clQdxb9GhouG9HdiBcTGtyd0orgq2S5kbkTMWtrj6IckLAj6EtcJll99sk1iI81y3MNTtT9pb6g1FZ63i/1NcvMGAyPzwD5CcikWlKfndk7Y6hY/b1rpyW86i0p37j26ubSLOJgog=
    - secure: uRUQ7WmpT+ztw+KZbV2Jh40S+iNXO+x3nESuWgopl8EWeH4hbdHSVELSMYyeRXSaDrN0BQC5k1SOia8yFiaPvk4T7ZR2HSkzOFJniZhEYGAj8LC+eE9gOKO97j9nHsxeD1dzHxGblboWim38zeB0ST/JjOuLJ8rqUYEcbQGOEDI9AzRSiqmSHarnZvPxe2A1CPzdhPIYtUlJ2JqkcxicqYyqlV6eQShyNPnI91wk18Ja9Mj69mm4XSwC5mTFbwTwIfcsyotP0VHVg1saY3w9W7Ymx2HIiEgftgn34ZZqjmGasoPTMXoqcJBBudVqoXMADoOcCA3wO89loenffE8EshDJY8JJP2uJu3EthA/93sL7KZYbfa8JTX+pvNkuX7TlQApIexfntifsXkCuQjr/0Gdtv7Iy/RxaDfu1IrH3BRVhBCK+uQ7NQPPz5mesUXsxzMW99nmeC03qoIpilqOwLIP+YYfzpOhaFMmcnYTISH4NEDwdNnBPJsG+29UiqobF6zmJnb4IPLP21gvthmtE1fAF6GcXXs4jjVelTs/ni5k1JMBSLLMrh4w/nIAWlbs8ZbSfSBeOm3sr+y5lOKY8ABpcVyuuw3qRLuemtuRFz35fDusWhckCRfMvCj5YWzp5+hUhbFITJdT7m+WbL2zo2oy6WL+mJRDc05m4MM+2UlE=

